name: Testing and Linting

on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    name: Melvin on ${{ matrix.os }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        python:
          - '3.9'
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install Melvin and dependencies
        run: pip install . pytest black flake8

      - name: Check formatting with black
        run: black --check .

      - name: Check style with flake8
        run: flake8

      - name: Test with pytest
        run: pytest

